# Generated by Django 3.0.5 on 2020-04-19 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200419_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 18, 3, 30, 996664, tzinfo=utc)),
        ),
    ]
