# Generated by Django 3.0.5 on 2020-04-19 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200420_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 18, 59, 58, 390641, tzinfo=utc)),
        ),
    ]
